### ISSUE TITLE
[Feature Request] Allow scrolling in player inventory

### ISSUE THREAD

**Issue by IronPiston** [quat1024/zenscroll#2]
It would be useful to be able to hold your cursor over an item in your inventory and scroll through, as opposed to being able to only do it in your hand. It would also be more intuitive, as you can only see the tooltip within the player inventory.

**Comment by quat1024** [comment]
lmao how did i forget this?

**Comment by quat1024** [comment]
actually hmmm, this is more edgecasey than I thought:

* possible conflicts with a lot with Item Scroller and similar mods (especially becaue Item Scroller in particular has a behavior for just about every modifier key)
* should you be able to scroll items inside chests, and not only your inventory? i mean of course yes, but how to implement it safely?
* lots of crazy modded slots to worry about: what if you scroll from ae2 or something? scroll a filter slot? what if you scroll an item into a slot it can't fit inside?
* & how can I be sure I won't add a million dupe bugs? :P

So I think this is a bigger can of worms than I thought it would be.

I'll stew on this for a bit.

**Comment by CreepyCre** [comment]
You could just check wether the Inventory the item is in is an instance of a (vanilla) player inventory and only allow scrolling in there. Not sure how to handle the MouseTweaks inventory scrolling though.

**Comment by IronPiston** [comment]
Would adding an addition keybind to scroll with alleviate this? 
Also, I think the player inventory is the only place this really makes sense, because the scrolling is probably more of a convenience thing rather than the only way to craft an item. Limiting it to only the hotbar and player inventory probably makes better sense than some sort of hacky blacklist/whitelist.

**Comment by VariableVixen** [comment]
I have to agree, don't even bother with letting you scroll in chests. It feels like it shouldn't be possible anyway, like you're reshaping the item or whatever in your inventory and that's fine - you have the thing! But in a storage inventory, it feels like you shouldn't be allowed to do that.

**Comment by quat1024** [comment]
Turns out this wasn't too hard to implement after all, when limited to in-inventory scrolling only!

My solution to the keybind problem is "fix it yourself", lol - I don't think conflicts with Item Scroller will be a huge problem, since you can rebind the modifier key to anything on your keyboard (unlike Item Scroller which has hardcoded Shifts, Alts, and Ctrls everywhere)

I still feel like this is gonna be dupe bug city somehow, so I added a server-side kill switch that rejects all in-inventory scroll events from clients if it's turned on.
