### ISSUE TITLE
NBT matching can be too lenient in some cases

### ISSUE THREAD

**Issue by GreatestFool** [quat1024/zenscroll#4]
So if you have wool to stick, you can loop back around to wool, and so on.

**Comment by quat1024** [comment]
Pretty sure this is already how it works - if it doesn't loop that's a bug

**Comment by GreatestFool** [comment]
Ah, then it's a bug. Mine doesn't work. I'll post a mod list in a while when I'm free.

**Comment by quat1024** [comment]
Hrmmm!

**Comment by GreatestFool** [comment]
[Here we go](https://ybin.me/p/3370dff410c814f6#zl5nsBJjRdqVbfUSJJAwfw2GL6mWSIT6XIInl7cft2Y=)

***e:*** Also, I forgot to mention. The item that I've been trying this with is the Biome Essence from Biomes O' Plenty. I've tried to have an essence without any tags change into one with tags. [Here's the script.](https://ybin.me/p/94f24e30f9835ced#Vh6vAo9RbydTH4IxZ7Pi7ZyZWgWXNRpF8kLiM4ZwAZE=) As you can see, I haven't quite figured out the grouping, but the normal one worked.

**Comment by quat1024** [comment]
Hmm, this is a corner case I didn't think of, thanks for bringing this up!

This is caused by ZenScroll being a little too lenient with how it matches NBT tags. Basically, if you hold a `<biomesoplenty:biome_essence>.withTag({biomeID: 93})`, when I try to figure out which item in the group you're scrolling from, that item matches against the regular old `<biomesoplenty:biome_essence>` in the group. Or in other words, it's always treating your scroll input as a scroll *away* from `<biomesoplenty:biome_essence>` with no NBT tag. Which, in the case of this particular scroll group, manifests as the scroll not doing anything.

(This sort of loose NBT matching is actually done on purpose so packmakers don't have to specify literally every single fragment of NBT data that might exist on an item to include it in a scroll group. It basically uses the same method that matches items against crafting recipes - think about how you can craft a recipe even if you rename one of the ingredients in an anvil first. I didn't consider how that could cause ambiguities!)

For now you could try reversing the order of the items in your script (putting the item with no NBT tag *last*) - that should cause ZenScroll to check the item with the more specific NBT tag first, since it checks front-to-back.

**Comment by quat1024** [comment]
I'll add some sort of `.strictMatch()` function in a bit.

**Comment by GreatestFool** [comment]
Awesome, thanks for the help.
